dependencies:
- name: exposecontroller
  version: 2.3.114
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.114
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: strimzi/strimzi-kafka-operator
  version: 0.15.0
  repository: http://strimzi.io/charts/
  alias: strimzi-operator

