dependencies:
- name: exposecontroller
  version: 2.3.114
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.114
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: strimzi-kafka-operator
  version: 0.15.0
  repository: http://strimzi.io/charts/
  alias: strimzi-operator
#- name: elasticsearch-operator
#  version: 0.1.3
#  repository: https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/charts/
#  alias: elasticsearch-operator
#- name: elasticsearch
#  version: 0.1.5
#  repository: https://raw.githubusercontent.com/upmc-enterprises/elasticsearch-operator/master/charts/
#  alias: elasticsearch
